### ISSUE TITLE
[Ring of Repair] Curios Support not working

### ISSUE THREAD

**Issue by NightmareTwilight** [kwpugh/gobber_forge#80] opened 2023-11-28 10:06 UTC
While the Ring of Repair is placeable in the ring slot, it is missing the code that actually repairs things while equipped. Would be amazing to see this fixed.

Version: 1.4.7
Forge: 40.2.10
Minecraft: 1.18.2

**Comment by tejaska** [comment] 2023-12-15 17:39
Seems like a duplicate of #65.

**Comment by kwpugh** [comment] 2024-02-20 21:23
Not supporting Curios

**Closed by kwpugh** 2024-02-20 21:23 UTC
